<?php
namespace Database\Seeders;

use App\Models\Category;
use App\Models\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title'             => 'Advanced Financial Modeling Using MS Excel',
                'category'          => 'Finance',
                'price'             => 350000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Master the art of building dynamic and robust financial models using Microsoft Excel. This programme covers advanced Excel techniques, scenario analysis, and valuation modelling used by finance professionals across Africa and beyond.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Financial Statement Analysis',
                'category'          => 'Finance',
                'price'             => 280000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Develop the skills to critically analyse and interpret financial statements for investment, credit, and strategic decision-making. Participants will learn to identify key performance indicators and detect red flags in corporate reporting.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Advanced Valuation Techniques',
                'category'          => 'Finance',
                'price'             => 320000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Explore DCF, comparable company analysis, precedent transactions, and LBO modelling in this comprehensive valuation programme. Participants leave with practical tools to value businesses across multiple industries.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Budget Preparation & Control',
                'category'          => 'Finance',
                'price'             => 260000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Learn to design, implement, and monitor budgets that align with organisational strategy. This course provides practical frameworks for financial planning, variance analysis, and budget control in corporate settings.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Investment Strategies & Portfolio Management',
                'category'          => 'Finance',
                'price'             => 350000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Gain a thorough understanding of investment theory and portfolio construction techniques. Topics include asset allocation, risk-return optimisation, modern portfolio theory, and alternative investments in African markets.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Cost Analysis & Management Accounting',
                'category'          => 'Finance',
                'price'             => 260000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Equip yourself with cost management tools essential for business decision-making. The programme covers cost behaviour, activity-based costing, marginal costing, and performance measurement for operational managers.',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Capital Structuring & Corporate Finance',
                'category'          => 'Finance',
                'price'             => 380000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Understand how firms make capital structure decisions, including the use of debt, equity, and hybrid instruments. This programme examines WACC, capital budgeting, dividend policy, and corporate restructuring strategies.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Financial Derivatives & Risk Management',
                'category'          => 'Finance',
                'price'             => 400000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'advanced',
                'description'       => 'Delve into the world of financial derivatives — options, futures, swaps, and forwards — and understand how they are used to hedge risk and enhance returns. Participants will gain hands-on exposure to derivative pricing models.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Alternative Dispute Resolution',
                'category'          => 'Legal',
                'price'             => 280000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Navigate disputes efficiently using mediation, arbitration, and negotiation techniques. This programme covers the legal framework for ADR in Nigeria, international arbitration conventions, and practical dispute resolution strategies.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Contract Management & Drafting',
                'category'          => 'Legal',
                'price'             => 300000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Develop expertise in drafting, reviewing, and managing commercial contracts. The course covers key contractual clauses, risk allocation, negotiation strategies, and contract lifecycle management.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Corporate Governance & Compliance',
                'category'          => 'Legal',
                'price'             => 330000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Understand the principles of effective corporate governance and regulatory compliance. Topics include board responsibilities, shareholder rights, the Nigerian Code of Corporate Governance, and anti-corruption frameworks.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Employment Law & HR Compliance',
                'category'          => 'Legal',
                'price'             => 260000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Stay compliant with Nigerian employment law and best HR practices. This course covers the Labour Act, employee rights, disciplinary procedures, termination, and workplace health and safety obligations.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Oil & Gas Agreements',
                'category'          => 'Oil & Gas',
                'price'             => 450000,
                'duration_days'     => 5,
                'mode'              => 'in_person',
                'level'             => 'advanced',
                'description'       => 'Gain in-depth knowledge of the key agreements governing Nigeria\'s upstream and downstream oil and gas sector. Topics include PSCs, JOAs, farmout agreements, and the Petroleum Industry Act regulatory landscape.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Power Purchase Agreements',
                'category'          => 'Oil & Gas',
                'price'             => 420000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'advanced',
                'description'       => 'Examine the structure and negotiation of power purchase agreements in Nigeria\'s evolving energy sector. Participants will analyse tariff structures, off-take risks, credit support mechanisms, and lender requirements.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Aircraft Leasing & Aviation Finance',
                'category'          => 'Finance',
                'price'             => 500000,
                'duration_days'     => 5,
                'mode'              => 'virtual',
                'level'             => 'advanced',
                'description'       => 'Explore the specialised world of aviation finance, covering aircraft leasing structures, JOLCO, enhanced equipment trust certificates, and the Cape Town Convention. Ideal for bankers, lawyers, and aviation professionals.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Real Estate Investment & Finance',
                'category'          => 'Real Estate',
                'price'             => 380000,
                'duration_days'     => 4,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Understand real estate investment analysis, property valuation, and financing structures in Nigeria. Participants will evaluate residential, commercial, and industrial property opportunities using current market data.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Private Equity & Venture Finance',
                'category'          => 'Finance',
                'price'             => 420000,
                'duration_days'     => 4,
                'mode'              => 'virtual',
                'level'             => 'advanced',
                'description'       => 'Navigate the private equity and venture capital landscape in Africa, covering fund structures, deal sourcing, due diligence, term sheets, and exit strategies. Essential for investors and corporate development professionals.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Project Appraisal & Infrastructure Finance',
                'category'          => 'Finance',
                'price'             => 350000,
                'duration_days'     => 4,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Learn to appraise and finance large-scale infrastructure projects using project finance techniques. Topics include feasibility studies, risk allocation, concession agreements, and blended finance in emerging markets.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Digital Marketing & Strategy',
                'category'          => 'Technology',
                'price'             => 250000,
                'duration_days'     => 3,
                'mode'              => 'virtual',
                'level'             => 'intermediate',
                'description'       => 'Build a comprehensive digital marketing strategy using data-driven insights and modern platforms. This course covers SEO, social media marketing, content strategy, email campaigns, and analytics for business growth.',
                'is_featured'       => false,
            ],
            [
                'title'             => 'Business Analysis & Process Improvement',
                'category'          => 'Management',
                'price'             => 280000,
                'duration_days'     => 3,
                'mode'              => 'in_person',
                'level'             => 'intermediate',
                'description'       => 'Develop the skills to analyse business processes, identify inefficiencies, and implement improvement initiatives. Topics include requirements gathering, process mapping, lean methodology, and stakeholder management.',
                'is_featured'       => false,
            ],
        ];

        foreach ($courses as $data) {
            $category = Category::where('name', $data['category'])->first();
            if (!$category) continue;

            Course::firstOrCreate(
                ['slug' => Str::slug($data['title'])],
                [
                    'category_id'       => $category->id,
                    'title'             => $data['title'],
                    'slug'              => Str::slug($data['title']),
                    'description'       => $data['description'],
                    'short_description' => substr($data['description'], 0, 150) . '...',
                    'price'             => $data['price'],
                    'duration_days'     => $data['duration_days'],
                    'mode'              => $data['mode'],
                    'level'             => $data['level'],
                    'is_published'      => true,
                    'is_featured'       => $data['is_featured'],
                    'max_delegates'     => 25,
                ]
            );
        }
    }
}
